server:
  port: 10001
  servlet:
    context-path: /
    multipart:
      max-file-size: -1 #文件上传大小无限制
  tomcat:
    uri-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
master:
  datasource:
    druid:
      url: jdbc:oracle:thin:@192.168.30.150:1521:orcl
      username: ioss_ptn
      password: ioss_ptn
      driver-class-name: oracle.jdbc.OracleDriver
      max-active: 10
      initial-size: 10
