server:
  port: 10001
  servlet:
    context-path: /
    multipart:
      max-file-size: -1 #文件上传大小无限制
  tomcat:
    uri-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
master:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_common_springboot?useUnicode=TRUE&characterEncoding=utf-8&useSSL=FALSE&serverTimezone=GMT%2B8
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      max-active: 10
      initial-size: 10

